# Generated by Django 2.0.5 on 2018-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
                ('qstn', models.CharField(max_length=45)),
                ('ans', models.CharField(max_length=45)),
            ],
        ),
    ]
